language: bash
dist: trusty
os:
- linux

addons:
  apt:
    packages:
    # install cross compilers for cgo support.
    - gcc-aarch64-linux-gnu
    - libc6-dev-arm64-cross
before_script:
- mkdir -p "${HOME}/travis/test"
script:
- touch ${HOME}/travis/test/test1.txt
before_deploy:
- rm -rf /tmp/*
- mkdir -p /tmp/travis/bashtest/
- cd /tmp/travis/bashtet/
deploy:
provider: script
script: bash scripts/deploy.sh
on:
branch: develop
