language: bash
dist: trusty
os:
- linux

cache:
  directories:
  - "${HOME}/bin"

addons:
  apt:
    packages:
    # install cross compilers for cgo support.
    - gcc-aarch64-linux-gnu
    - libc6-dev-arm64-cross
before_script:
- mkdir -p "${HOME}/travis/test"
script:
- touch ${HOME}/travis/test/test1.txt
